version: "3.8"
services:
    ecommerce-ui:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        ports:
            - "3000:3000"
        container_name: ecommerce-ui
        stdin_open: true
        tty: true
        volumes:
            - .:/app
            - /app/node_modules
